{
 "title": "World Map",
 "tags": [
  "logs",
  "map"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "event_filter",
    "label": "Event Filter",
    "query": "crash,player,unknown,timeout,security,resource,heatmap,explosion,deaths"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "World Map",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{event=~\"$event_filter\"} | json"
    }
   ]
  },
  {
   "title": "Total per event",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{event=~\"$event_filter\"} | json"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{event=~\"$event_filter\"} | json | line_format \"{{printf \\\"%s\\\" .message}}\""
    }
   ]
  },
  {
   "title": "Top Crash Reasons",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{event=\"crash\"} | json"
    }
   ]
  }
 ]
}